### ISSUE TITLE
change demo page link to http://gitbucket-community.herokuapp.com/ ?

### ISSUE THREAD

**Issue by xuwei-k** [gitbucket/gitbucket-news#16]
There are more plugins available than http://gitbucket.herokuapp.com/

WDYT?

- https://github.com/gitbucket/gitbucket-news/blob/1454823ed827c9daaf39d6aadc8f5c1ef5c43040/_includes/header.html#L21
- https://github.com/gitbucket/gitbucket/issues/1309

**Comment by takezoe** [comment]
@McFoggy According to my memory, I had proposed you to add community plugins to gitbucket.herokuapp.com instead of gitbucket-community.herokuapp.com. But you did not agree with it. Why was it?

**Comment by McFoggy** [comment]
@takezoe I do not think I fully disagreed about that. But it can make sense to keep a demo infrastructure with only _approved_ gitbucket plugins , ie the ones coming from [gitbucket](https://github.com/gitbucket) community.

We can step back from this position but I would advice to think about it twice ; having 2 separated environments brings some advantages especially in ensuring that we will ALWAYS have a running platform gitbucket.herokuapp.com with the official plugins without having some pressure in having everything (all plugins) up and running for each release.
Take the example of the current `4.8` release, I am not sure that all plugins run correctly due to the changes in the rendering helper classes of gitbucket. The community platform is good to detect those changes and to play with all plugins. But having a stable platform with stable plugins is also a good thing. 

If you want, we can simplify the management of the [gitbucket.herokuapp.com](https://github.com/gitbucket/gitbucket.herokuapp.com) project by reusing the script I have created on [gitbucket-community.herokuapp.com](https://github.com/gitbucket/gitbucket.herokuapp.com)

**Comment by takezoe** [comment]
@McFoggy Thanks for your reply.

> having 2 separated environments brings some advantages especially in ensuring that we will ALWAYS have a running platform gitbucket.herokuapp.com with the official plugins without having some pressure in having everything (all plugins) up and running for each release.

It's reasonable. Indeed, there is possibility that gitbucket-community.herokuapp.com can't be updated immediately after GitBucket release by plugin compatibility.
